In [1]:
import numpy as np
#1.1

a = np.arange(0,50)
a = a.reshape(5,10)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [2]:
#1.2
b = a[-2:,2:7]
b

array([[32, 33, 34, 35, 36],
       [42, 43, 44, 45, 46]])

In [3]:
#1.3
rng = np.random.default_rng()
c = rng.normal(size=(5,5))
c

array([[-1.03375437, -0.58853152, -0.63602385, -0.04743185,  0.95276878],
       [-0.44805557, -1.73386479, -1.16608288,  1.41575671, -1.37445251],
       [ 0.42587775,  0.03560661,  1.43935611,  0.41454029,  1.3820579 ],
       [-0.6946726 ,  0.84364253,  1.68891314,  0.60568018, -0.91367264],
       [ 0.9336012 ,  0.55206601, -0.1698509 , -0.38184659, -0.0980661 ]])

In [4]:
c_mean = c.mean()
c_mean

np.float64(0.05614244256282058)

In [5]:
c_adjusted = c - c_mean
c_adjusted.mean()

np.float64(4.218847493575595e-17)

In [6]:
#1.4
d = rng.integers(low=0,high=101,size=(20))
d

array([81, 86, 87, 37,  5,  1, 74,  8, 16, 39, 57, 41, 60,  7, 17, 11, 35,
       65,  3, 33])

In [7]:

[x for x in d if x > 50]

[np.int64(81),
 np.int64(86),
 np.int64(87),
 np.int64(74),
 np.int64(57),
 np.int64(60),
 np.int64(65)]

In [8]:
e = d
e[e<30] = -1
e

array([81, 86, 87, 37, -1, -1, 74, -1, -1, 39, 57, 41, 60, -1, -1, -1, 35,
       65, -1, 33])

In [9]:
import pandas as pd
import numpy as np

data = {
    'Order_ID': [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
    'Product': ['Laptop', 'Mouse', 'Monitor', 'Mouse', 'Keyboard', 'Laptop', 'Monitor', 'Keyboard', 'Mouse', 'Laptop'],
    'Category': ['Electronics', 'Accessories', 'Electronics', 'Accessories', 'Accessories', 'Electronics', 'Electronics', 'Accessories', 'Accessories', 'Electronics'],
    'Region': ['North', 'South', 'West', 'North', 'West', 'South', 'North', 'West', 'South', 'North'],
    'Date': ['2024-01-15', '2024-01-16', '2024-01-18', '2024-01-20', '2024-01-21', '2024-02-05', '2024-02-10', '2024-02-15', '2024-02-20', '2024-03-01'],
    'Quantity': [1, 5, 2, np.nan, 3, 1, 2, 4, 10, 2],
    'Unit_Price': [1000, 25, 300, 25, 45, 1000, 300, 45, 25, 1200]
}

df = pd.DataFrame(data)
df

   Order_ID   Product     Category Region        Date  Quantity  Unit_Price
0       101    Laptop  Electronics  North  2024-01-15       1.0        1000
1       102     Mouse  Accessories  South  2024-01-16       5.0          25
2       103   Monitor  Electronics   West  2024-01-18       2.0         300
3       104     Mouse  Accessories  North  2024-01-20       NaN          25
4       105  Keyboard  Accessories   West  2024-01-21       3.0          45
5       106    Laptop  Electronics  South  2024-02-05       1.0        1000
6       107   Monitor  Electronics  North  2024-02-10       2.0         300
7       108  Keyboard  Accessories   West  2024-02-15       4.0          45
8       109     Mouse  Accessories  South  2024-02-20      10.0          25
9       110    Laptop  Electronics  North  2024-03-01       2.0        1200

In [10]:
#2.1
df[:5]

   Order_ID   Product     Category Region        Date  Quantity  Unit_Price
0       101    Laptop  Electronics  North  2024-01-15       1.0        1000
1       102     Mouse  Accessories  South  2024-01-16       5.0          25
2       103   Monitor  Electronics   West  2024-01-18       2.0         300
3       104     Mouse  Accessories  North  2024-01-20       NaN          25
4       105  Keyboard  Accessories   West  2024-01-21       3.0          45

In [11]:
df.dtypes

Order_ID        int64
Product           str
Category          str
Region            str
Date              str
Quantity      float64
Unit_Price      int64
dtype: object

In [12]:
pd.to_datetime(df['Date'])
df

   Order_ID   Product     Category Region        Date  Quantity  Unit_Price
0       101    Laptop  Electronics  North  2024-01-15       1.0        1000
1       102     Mouse  Accessories  South  2024-01-16       5.0          25
2       103   Monitor  Electronics   West  2024-01-18       2.0         300
3       104     Mouse  Accessories  North  2024-01-20       NaN          25
4       105  Keyboard  Accessories   West  2024-01-21       3.0          45
5       106    Laptop  Electronics  South  2024-02-05       1.0        1000
6       107   Monitor  Electronics  North  2024-02-10       2.0         300
7       108  Keyboard  Accessories   West  2024-02-15       4.0          45
8       109     Mouse  Accessories  South  2024-02-20      10.0          25
9       110    Laptop  Electronics  North  2024-03-01       2.0        1200

In [13]:
#2.2
x = df['Quantity'].tolist()
x.remove(x[3])
x.insert(3, np.array(x).mean())
df['Quantity'] = x
df

   Order_ID   Product     Category Region        Date   Quantity  Unit_Price
0       101    Laptop  Electronics  North  2024-01-15   1.000000        1000
1       102     Mouse  Accessories  South  2024-01-16   5.000000          25
2       103   Monitor  Electronics   West  2024-01-18   2.000000         300
3       104     Mouse  Accessories  North  2024-01-20   3.333333          25
4       105  Keyboard  Accessories   West  2024-01-21   3.000000          45
5       106    Laptop  Electronics  South  2024-02-05   1.000000        1000
6       107   Monitor  Electronics  North  2024-02-10   2.000000         300
7       108  Keyboard  Accessories   West  2024-02-15   4.000000          45
8       109     Mouse  Accessories  South  2024-02-20  10.000000          25
9       110    Laptop  Electronics  North  2024-03-01   2.000000        1200

In [14]:
#2.3
df['Total_Sales'] = df['Quantity'] * df['Unit_Price']
df

,Order_ID,Product,Category,Region,Date,Quantity,Unit_Price,Total_Sales
0,101,Laptop,Electronics,North,2024-01-15,1.000000,1000,1000.000000
1,102,Mouse,Accessories,South,2024-01-16,5.000000,25,125.000000
2,103,Monitor,Electronics,West,2024-01-18,2.000000,300,600.000000
3,104,Mouse,Accessories,North,2024-01-20,3.333333,25,83.333333
4,105,Keyboard,Accessories,West,2024-01-21,3.000000,45,135.000000
5,106,Laptop,Electronics,South,2024-02-05,1.000000,1000,1000.000000
6,107,Monitor,Electronics,North,2024-02-10,2.000000,300,600.000000
7,108,Keyboard,Accessories,West,2024-02-15,4.000000,45,180.000000
8,109,Mouse,Accessories,South,2024-02-20,10.000000,25,250.000000
9,110,Laptop,Electronics,North,2024-03-01,2.000000,1200,2400.000000

In [15]:
#2.4
high_value_sales = df.query(f"Total_Sales > 500")
high_value_sales

,Order_ID,Product,Category,Region,Date,Quantity,Unit_Price,Total_Sales
0,101,Laptop,Electronics,North,2024-01-15,1.0,1000,1000.0
2,103,Monitor,Electronics,West,2024-01-18,2.0,300,600.0
5,106,Laptop,Electronics,South,2024-02-05,1.0,1000,1000.0
6,107,Monitor,Electronics,North,2024-02-10,2.0,300,600.0
9,110,Laptop,Electronics,North,2024-03-01,2.0,1200,2400.0

In [16]:
len(high_value_sales)

5

In [17]:
#2.5
grouped = df.groupby('Category')
grouped['Total_Sales'].agg(['sum'])

                     sum
Category
Accessories   773.333333
Electronics  5600.000000

In [18]:
grouped = df.groupby('Region')
grouped['Unit_Price'].agg(['mean'])

          mean
Region
North   631.25
South   350.00
West    130.00

In [19]:
#2.6
df["Region"] = [x.upper() for x in df["Region"].tolist()]
df

,Order_ID,Product,Category,Region,Date,Quantity,Unit_Price,Total_Sales
0,101,Laptop,Electronics,NORTH,2024-01-15,1.000000,1000,1000.000000
1,102,Mouse,Accessories,SOUTH,2024-01-16,5.000000,25,125.000000
2,103,Monitor,Electronics,WEST,2024-01-18,2.000000,300,600.000000
3,104,Mouse,Accessories,NORTH,2024-01-20,3.333333,25,83.333333
4,105,Keyboard,Accessories,WEST,2024-01-21,3.000000,45,135.000000
5,106,Laptop,Electronics,SOUTH,2024-02-05,1.000000,1000,1000.000000
6,107,Monitor,Electronics,NORTH,2024-02-10,2.000000,300,600.000000
7,108,Keyboard,Accessories,WEST,2024-02-15,4.000000,45,180.000000
8,109,Mouse,Accessories,SOUTH,2024-02-20,10.000000,25,250.000000
9,110,Laptop,Electronics,NORTH,2024-03-01,2.000000,1200,2400.000000